from enum import Enum

class StockMovAdjTypeEnums(str,Enum):
    PURCHASE="PURCHASE"
    SALES="SALES"
    ONLINE_SALES="ONLINE_SALES"
    OFFLINE_SALES="OFFLINE_SALES"
    SALES_RETURN="SALES_RETURN"
    ONLINE_SALES_RETURN="ONLINE_SALES_RETURN"
    OFFLINE_SALES_RETURN="OFFLINE_SALES_RETURN"
    ONLINE_SALES_EXCHANGE="ONLINE_SALES_EXCHANGE"
    OFFLINE_SALES_EXCHANGE="OFFLINE_SALES_EXCHANGE"
    ADJUSTMENT="ADJUSTMENT"

class StockMovAdjItemTypeEnums(str,Enum):
    INCREMENT="INCREMENT"
    DECREMENT="DECREMENT"
    DIRECT="DIRECT"

